version: "3.7"

services:
  web:
    image: lnbitsdocker/lnbits:7134821@sha256:c5e58fa94e01180a9c538b0d5a66dc9824c900c6671e8c5ede9adb270d885579
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    environment:
      # Global
      LNBITS_BIND: "0.0.0.0:5000"

      # Lightning
      LNBITS_BACKEND_WALLET_CLASS: OpenNodeWallet
      OPENNODE_API_ENDPOINT: https://dev-api.opennode.com
      OPENNODE_KEY: ${OPENNODE_KEY}

      # App
      LNBITS_SITE_TITLE: "LNbits - Sovryn"
      LNBITS_DEFAULT_WALLET_NAME: "LNbits wallet"
      LNBITS_DISABLED_EXTENSIONS: "amilk"